// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnbtakoboaskfulrujox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImduYnRha29ib2Fza2Z1bHJ1am94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MjExMTksImV4cCI6MjA4Mzk5NzExOX0.M41J0Se0AbC1_GOWWmz5vB1AHT8rVEFR-uK9ShsZ-z8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});